fr3_left__controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    joint_impedance_controller:
      type: "fr3_controllers/JointImpedanceController"
      k_gains: [24.0, 24.0, 24.0, 24.0, 10.0, 6.0, 2.0]
      d_gains: [2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 0.5]
    franka_robot_state_broadcaster:
      type: "franka_robot_state_broadcaster/FrankaRobotStateBroadcaster"

fr3_right__controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    joint_impedance_controller:
      type: "fr3_controllers/JointImpedanceController"
      k_gains: [24.0, 24.0, 24.0, 24.0, 10.0, 6.0, 2.0]
      d_gains: [2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 0.5]
    franka_robot_state_broadcaster:
      type: "franka_robot_state_broadcaster/FrankaRobotStateBroadcaster"